### ISSUE TITLE
Failed to load a language-coffee-script package grammar

### ISSUE THREAD

**Issue by minozzang508** [atom/language-coffee-script#131] opened 2017-05-30 07:17 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-coffee-script](https://github.com/atom/language-coffee-script) package 0.48.6

### Stack Trace

Failed to load a language-coffee-script package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\minho\AppData\Local\atom\app-1.17.2\resources\app\node_modules\language-coffee-script\grammars\coffeescript (literate).json' in C:\Users\minho\AppData\Local\atom\app-1.17.2\resources\app\node_modules\language-coffee-script\grammars\coffeescript (literate).json

Error: ENOENT: no such file or directory, open 'C:\Users\minho\AppData\Local\atom\app-1.17.2\resources\app\node_modules\language-coffee-script\grammars\coffeescript (literate).json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/language-coffee-script/grammars/coffeescript (literate).json:1:1
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
emmet 2.4.3 
minimap 4.28.2 
script 3.15.0 
terminal-plus 0.14.5 
```

**Comment by rsese** [comment] 2017-05-30 20:27
Closing as a duplicate of https://github.com/atom/language-java/issues/94 but can you try re-installing @minozzang508?

**Closed by rsese** 2017-05-30 20:27 UTC
