### ISSUE TITLE
Issues with Literate Coffeescript

### ISSUE THREAD

**Issue by frabert** [atom/language-coffee-script#55] opened 2015-05-23 13:20 UTC
The following [file](https://gist.github.com/frabert/1b9b8c90d5dcef520d99) is rendered as such in Atom:
![Syntax image](http://i.imgur.com/Swl3iuV.png)
As can be seen, the source blocks are not highlighted. Anyone encountering this too?
Please note that the markdown parts are highlighted correctly in the same file.
Atom 0.201

**Comment by frabert** [comment] 2015-05-23 13:48
I've noticed that removing the "\`\`\`coffee \`\`\`" blocks solves the situation. Any clue?

**Comment by vijithassar** [comment] 2015-11-22 23:19
Literate Coffeescript uses the [classic Markdown method of demarcating code blocks](http://coffeescript.org/#literate), which is [based on indentation](https://daringfireball.net/projects/markdown/syntax#precode) rather than the backticks used for [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks). Files written that way highlight properly, though [function folding is broken](https://github.com/atom/atom/issues/8879). If you'd like to use GitHub-style code blocks, I've written a [language agnostic preprocessing script](https://github.com/vijithassar/lit/) which can help with that.

**Comment by 50Wliu** [comment] 2016-02-05 03:15
Closing as it appears that Literate Coffeescript does not support fenced code blocks.

@frabert, @vijithassar if I'm wrong, please comment here and I'll reopen this issue.

**Closed by 50Wliu** 2016-02-05 03:15 UTC

**Comment by vijithassar** [comment] 2016-02-05 05:16
The problem is not that I want Literate CoffeeScript to support fenced code blocks, I'm pointing out that Atom's function folding commands should not break when I use it to write Literate CoffeeScript code.
