### ISSUE TITLE
Long array with indenting breaks highlighting

### ISSUE THREAD

**Issue by TeardropInc** [atom/language-coffee-script#46] opened 2015-01-21 23:39 UTC
Steps to reproduce:

1. Create new file.

2. Enter the following code.
```coffeescript
state_enums = [ 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'GU', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MP', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'AS', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VI', 'VA', 'WA', 'WV', 'WI', 'WY' ]
state_enums.push('ON', 'QC', 'NS', 'NB', 'MB', 'BC', 'PE', 'AB', 'NL') # Canada`
```

3. Now indent the code once by selecting it all and doing `cmd`/`ctrl` + `]`

What you should see is the code loses it's highlighting after 20 or so index entries but this seems to only be the case when it is indented. Outdenting restores the highlighting.

![screen shot 2015-01-21 at 3 38 33 pm](https://cloud.githubusercontent.com/assets/387930/5847577/97d14adc-a183-11e4-88d2-6c769cb3f509.png)

**Comment by kevinsawicki** [comment] 2015-01-21 23:42
This looks like a duplicate of https://github.com/atom/atom/issues/1667 where the tokenizer stops after a certain number of tokens.

**Closed by kevinsawicki** 2015-01-21 23:42 UTC

**Comment by TeardropInc** [comment] 2015-01-23 17:57
OK, thanks.
