### ISSUE TITLE
Starting a line with `form` causes incorrect next-line indentation

### ISSUE THREAD

**Issue by davepeck** [atom/language-coffee-script#84] opened 2016-02-09 23:44 UTC
Using standard (_not_ literate) coffeescript, if you type a line that starts with `form`, the next line will be incorrectly indented.

![mystery_indentation](https://cloud.githubusercontent.com/assets/53165/12934518/f4fdb68e-cf43-11e5-8d4d-131983394c91.gif)

`atom` 1.5.0, `language-coffee-script` 0.46.0, reproduces in safe mode

**Comment by davepeck** [comment] 2016-02-10 00:03
Ah, okay. Starting the line with `form` works as well as `forz` -- the key is that you started the line with `for`.

There are related issues that don't require matches at the beginning of the line. For example, type `hello_class` on a line and hit return; you'll also be intended. (Oddly, `hello_for`, and `hello_form` don't have the same impact.)

**Comment by 50Wliu** [comment] 2016-02-10 00:40
The issue is probably that the indentation regexes aren't checking to see that the phrase it's trying to match is a standalone word and not a part of a larger word.

**Comment by 50Wliu** [comment] 2016-02-10 00:41
Yeah...https://github.com/atom/language-coffee-script/blob/master/settings/language-coffee-script.cson#L13.  I'll create a PR.

**Comment by davepeck** [comment] 2016-02-10 00:42
(Thanks; I didn't know where to look for indentation-related issues, but sure looks like the culprit.)

**Comment by 50Wliu** [comment] 2016-02-27 22:32
Fixed by #85.

**Closed by 50Wliu** 2016-02-27 22:32 UTC
Labels: auto-indent, bug
