### ISSUE TITLE
Function indicator fails when newline in argument list

### ISSUE THREAD

**Issue by dane-johnson** [atom/language-coffee-script#125] opened 2017-05-15 19:48 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Define a function
2. Put a newline in the arg list

**Expected behavior:** [What you expect to happen]
The function name remained highlighted as such

**Actual behavior:** [What actually happens]
The function name highlighting changes to indicated a variable

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.11.0

Mac OS Sierra
v10.12.4

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![highlight-bug](https://cloud.githubusercontent.com/assets/10768827/26076055/1c4217cc-397d-11e7-8955-520518f2b2d1.gif)

**Comment by 50Wliu** [comment] 2017-05-15 20:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #25. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-15 20:29 UTC
