### ISSUE TITLE
Syntax highlight issue with destructuring expressions within string interpolations

### ISSUE THREAD

**Issue by bkuri** [atom/language-coffee-script#97] opened 2016-07-10 05:32 UTC
![screenshot at 00-28-59](https://cloud.githubusercontent.com/assets/138886/16711842/7adc117a-4635-11e6-8717-67437fa4064a.png)

**Comment by 50Wliu** [comment] 2016-07-15 11:20
Confirmed using language-coffee-script 0.47.1.

```coffee
output.write "<script>#{ compile(source, {bare}) }</script>"
```

**Comment by t9md** [comment] 2016-12-01 06:22
I believe issue below has same cause, so put here.

![incorrect-hl-object-destructuring-assignment](https://cloud.githubusercontent.com/assets/155205/20783752/3c2be4b2-b7d9-11e6-8308-393654394bfb.gif)

## Problem: Using object destructuring assignment make syntax-highlight wired after that row.

Below is exactly same code I used in above GIF.

```coffeescript
  getPreviousStartOfSentence: (fromPoint) ->
    scanRange = new Range(fromPoint, [0, 0])
    foundPoint = null
    @editor.backwardsScanInBufferRange @sentenceRegex, scanRange, ({range, match, stop, matchText}) =>
      if match[1]?

        # [LOOK] Comment in/out change syntax highlight to EOF
        {start: {row: startRow}, end: {row: endRow}} = range

        if not @isBlankRow(endRow) and @isBlankRow(startRow)
          point = @getFirstCharacterPositionForRow(endRow)
          if point.isLessThan(fromPoint)
            foundPoint = point
          else
            return if @skipBlankRow
            foundPoint = @getFirstCharacterPositionForRow(startRow)
      else
        if range.end.isLessThan(fromPoint)
          foundPoint = range.end
      stop() if foundPoint?
    foundPoint ? scanRange.start
```

**Comment by 50Wliu** [comment] 2016-12-01 15:25
@t9md your issue is actually different.  Can you please test out #106?

**Comment by t9md** [comment] 2016-12-01 15:58
@50Wliu

Thanks, I tried `wl-more-destructuring-fixes` branch and was OK, FIXED for the issue "object destructuring assignment make syntax-highlight wired".

Thanks

![incorrect-hl-object-destructuring-assignment-fixed](https://cloud.githubusercontent.com/assets/155205/20800867/5037fdaa-b82a-11e6-872b-76084c923ddc.gif)

Versions I checked with.

- Stable
```
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

- Beta
```
Atom    : 1.13.0-beta6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by t9md** [comment] 2016-12-01 18:05
@50Wliu Is this accidentally closed?

I didn't checked for original issue "Syntax highlight issue with destructuring expressions within string interpolations".

**Comment by 50Wliu** [comment] 2016-12-01 18:17
Whoops!  Didn't think my commit message would close it.

**Comment by dcalhoun** [comment] 2017-01-09 18:59
This may not be directly related, but I've seen the syntax highlighting break with the following as well. Commenting out the first line will change the colors of the second.

```coffeescript
foo = [0, [1, 2]]
this.$el.remove()
```

Let me know if I should create a separate issue.

**Comment by 50Wliu** [comment] 2017-01-09 19:31
@dcalhoun I can't reproduce that using the latest language-coffee-script version so I'm going that it's been fixed.

**Comment by ashthespy** [comment] 2017-04-01 23:45
Also unsure if related, but have issues with using `/` inside a string like so:

![](https://files.gitter.im/jashkenas/coffeescript/RDcc/image.png)


with `v 0.48.5`

**Comment by 50Wliu** [comment] 2017-04-02 01:00
I believe that's been fixed in the latest version, and should be out in Atom 1.16.0 or 1.17.0.

**Closed** 2017-09-04 13:19 UTC
Labels: bug
