### ISSUE TITLE
Can't set coffee script tab size to "2" while having global editor tab size at size not equal to 2

### ISSUE THREAD

**Issue by dparton** [atom/language-coffee-script#93] opened 2016-04-27 17:55 UTC
Repro steps:
1. Change the default editor tab length to anything other than 2. (I use 4 globally)
2. Try to change Coffee tab length to 2.

Actual: The setting is removed and then replaced by whatever value is set in #1
Expected: The setting remains at 2.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/12650318/14862465/6d77334c-0c66-11e6-970e-a8eef013b72e.gif)

**Comment by 50Wliu** [comment] 2016-04-27 20:39
This is a duplicate of atom/settings-view#774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-27 20:39 UTC
