### ISSUE TITLE
Syntax highlighting fail after a for loop over array of arrays of numbers

### ISSUE THREAD

**Issue by romaincointepas** [atom/language-coffee-script#107] opened 2016-12-15 14:39 UTC
The following line will screw up highlighting for all the lines after it:

```coffee
for maxResolution in [[1920, 1080], [1280, 720]]
```

The problem seems to be the array of arrays of Numbers.

Note: the issue doesn't happen when using any of the following:

```coffee
for maxResolution in [1920, 1080]
```

```coffee
for maxResolution in [['1920', 1080], [1280, 720]]
```

**Comment by 50Wliu** [comment] 2016-12-15 15:27
Pretty sure this was a problem with destructuring assignments that has been fixed as of `master` because I can't reproduce it.

**Closed by 50Wliu** 2016-12-15 15:27 UTC
