### ISSUE TITLE
Arrays in arrays screws over highlighter

### ISSUE THREAD

**Issue by DerpfacePython** [atom/language-coffee-script#105] opened 2016-11-12 00:26 UTC
For some reason, something like this:
```coffee
test_var = [[]]
```

gets turned into this:

![bug](https://cloud.githubusercontent.com/assets/14177193/20234008/1dfd2c08-a8ca-11e6-9b3d-bb5c747668a1.PNG)

Also, something like this:

```coffee
first = ["This works fine"]
second = [[0, 0], [0, 0]]
third = ["This doesn't work properly"]

test = ->
  alert(third.join("\n"))
```

completely screws over the highlighting, turning it into this:

![biggerbug](https://cloud.githubusercontent.com/assets/14177193/20234061/c46ac03c-a8ca-11e6-95dc-6d32dc21addd.PNG)

Upon closer inspection, the first brace is `punctuation definition destructuring begin bracket square coffee`, and then the second brace is `meta brace square coffee`.

**Comment by 50Wliu** [comment] 2016-11-12 05:39
Cannot reproduce using the latest version of language-coffee-script.  This should be fixed in Atom 1.13.0.

**Closed by 50Wliu** 2016-11-12 05:39 UTC
